#cloud-config
hostname: ${hostname}
manage_etc_hosts: true
package_upgrade: true
locale: en_GB.UTF-8
users:
  - name: nessie
    gecos: Loch nessies user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id: None
    lock_passwd: true
bootcmd:
  - |
    cat>/usr/local/bin/nessus-cloudinit.sh<<EOF
${bootstrap-tools}
    EOF
  - 'chmod 0755 /usr/local/bin/pentest-cloudinit.sh'
  - '/usr/local/bin/nessus-cloudinit.sh >> /var/log/nessus-cloudinit.log 2>&1'
