health_status_notify: &health_status_notify
  put: health-notification


resource_types:
  - name: http-api
    type: docker-image
    source:
      repository: gdscyber/http-api-resource

resources:
  - name: cyber-security-nessus-git
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/cyber-security-nessus.git
      branch: master

  - name: health-notification
    type: http-api
    source:
      uri: https://((health_host_prod))/?alert_type=concourse$&alert_name=health
      method: POST
      headers:
        Authorization: "Bearer ((health_token_prod))"
      json:
        service: "{service}"
        state: "{health}"
        message: "{message}"
        pipeline: "{BUILD_PIPELINE_NAME}"
        job: "{BUILD_JOB_NAME}"
        build_number: "{BUILD_NAME}"
      service: "Nessus Pipeline"


jobs:
  - name: nessus_deploy
    serial: true
    plan:
      - get: cyber-security-nessus-git
        trigger: true
      - task: terraform_deploy
        config:
          inputs:
          - name: cyber-security-nessus-git
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdscyber/cyber-security-concourse-base-image
          run:
            path: /bin/bash
            args:
              - -c
              - |
                pip install pipenv

                cd cyber-security-nessus-git
                pipenv --python 3.7
                pipenv install

                make zip
                source /usr/local/bin/sts-assume-role.sh 'arn:aws:iam::676218256630:role/nessus_role' 'eu-west-2'
                cd terraform
                terraform init
                terraform apply --auto-approve
                cd ..
                pipenv run python generate_api_keys.py
        on_success:
          <<: *health_status_notify
          params:
            message: "Nessus instance built successfully."
            health: healthy
        on_failure:
          <<: *health_status_notify_for_prod
          params:
            message: "Failed to build Nessus instance"
            health: unhealthy
